dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: node-http-demo1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.28
- name: nodejs-bdd-testing
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: nodejsscan
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: simple-node-js-react-npm-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
